name: brewhub
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^2.12.8
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/doggo.jpg
    - assets/background.jpg
    - assets/google.png
    - assets/brewhub.png
    - assets/brewhub_logo.png
    - assets/doodle.png
    - assets/faces/default.png
    - assets/hub/default.png
    - assets/hub/hub1.png
    - assets/hub/hub2.png
    - assets/images/
    - assets/images/map/
    - assets/images/fPlayer_elf.png
    