name: brewhub
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/doggo.jpg
    - assets/background.jpg
    - assets/google.png
    - assets/brewhub.png
    - assets/brewhub_logo.png
    - assets/homeBg.jpg
    - assets/faces/alex.png
    - assets/faces/clara.png
    - assets/faces/brian.png
    - assets/faces/sarah.png
    - assets/faces/michael.png
    - assets/faces/jasmine.png
    - assets/faces/edward.png
    - assets/faces/nina.png
    - assets/faces/gpt.png
    - assets/faces/Tospericargerja.png