[package]
name = "brew_hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.1"
tokio = { version = "1.32.0", features = ["full"] }
futures = "0.3"
tokio-stream = "0.1.5"
